/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controller.ControllerPermisos;
import Controller.ControllerTerceros;
import javax.swing.JOptionPane;
/**
 *
 * @author erick
 */
public class ActualizarTercero extends javax.swing.JFrame {
    protected ControllerTerceros controller;
    protected ControllerPermisos permiso;
    /**
     * Creates new form NuevoTercero
     * @param permiso
     */
    
    public ActualizarTercero() {
        //this.permiso=permiso;
        initCustomComponents();
        this.setLocationRelativeTo(null);
    }
    public ControllerPermisos getPermisos(){
        return this.permiso;
    }
    public void setPermisos(ControllerPermisos permiso){
        this.permiso=permiso;
    }
    @SuppressWarnings("unchecked")
    protected void initCustomComponents(){
        initComponents();
        this.controller=new ControllerTerceros();
        this.controller.llenarComboTipoDocumento(this.cmbtipodocumento);
    }
    public ControllerPermisos getPermiso(){
        return this.permiso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        utilDateModel1 = new org.jdatepicker.impl.UtilDateModel();
        utilDateModel2 = new org.jdatepicker.impl.UtilDateModel();
        utilDateModel3 = new org.jdatepicker.impl.UtilDateModel();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        cmbtipodocumento = new com.frame.Conf.ComboBoxCustom();
        txtdocumento = new com.frame.Conf.TextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new com.frame.Conf.TextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        txtdireccion = new com.frame.Conf.TextFieldCustom();
        txtdireccion2 = new com.frame.Conf.TextFieldCustom();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelefono1 = new com.frame.Conf.TextFieldCustom();
        jLabel7 = new javax.swing.JLabel();
        txttelefono2 = new com.frame.Conf.TextFieldCustom();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new com.frame.Conf.TextFieldCustom();
        txtfechanacimiento = new com.frame.Conf.DatePickerCustom();
        jLabel9 = new javax.swing.JLabel();
        chkusuario = new javax.swing.JCheckBox();
        chkcliente = new javax.swing.JCheckBox();
        chkproveedor = new javax.swing.JCheckBox();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Tercero");

        jLabel1.setText("Documento");

        jLabel2.setText("Tipo Documento");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtdocumento.setPlaceholder("Digite documento");
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyReleased(evt);
            }
        });

        jLabel3.setText("Nombre Completo");

        txtnombre.setPlaceholder("Digite Nombre Completo");

        jLabel4.setText("Dirección1");

        txtdireccion.setPlaceholder("Digite Dirección");

        txtdireccion2.setPlaceholder("Digite Dirección");

        jLabel5.setText("Dirección2");

        jLabel6.setText("Teléfono1");

        txttelefono1.setPlaceholder("Digite Teléfono");

        jLabel7.setText("Teléfono2");

        txttelefono2.setPlaceholder("Digite Teléfono");

        jLabel8.setText("Email");

        txtemail.setPlaceholder("Digite Email");

        jLabel9.setText("Fecha de Nacimiento");

        chkusuario.setText("Vendedor");

        chkcliente.setText("Cliente");

        chkproveedor.setText("Proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkusuario)
                        .addGap(18, 18, 18)
                        .addComponent(chkcliente)
                        .addGap(18, 18, 18)
                        .addComponent(chkproveedor)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbtipodocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkusuario)
                    .addComponent(chkcliente)
                    .addComponent(chkproveedor))
                .addGap(18, 18, 18)
                .addComponent(btnguardar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        try{
            if(this.permiso.getGRABAR()){
                this.controller=new ControllerTerceros();
                //this.controller.grabarTercero(this);
            }else{
                JOptionPane.showMessageDialog(null,"No tiene permisos para grabar","Permiso",2);
            }
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,err.getMessage(),err.getCause().getMessage(),0);
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtdocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyReleased
        if(!this.txtdocumento.getText().equals("")){
            System.out.println("Texto: "+this.txtdocumento.getText());
        }
    }//GEN-LAST:event_txtdocumentoKeyReleased
    public String getTipoDocumento(){
        return this.cmbtipodocumento.getKey();
    }
    public String getDocumento(){
        return this.txtdocumento.getText();
    }
    public String getNombre(){
        return this.txtnombre.getText();
    }
    public String getDireccion1(){
        return this.txtdireccion.getText();
    }
    public String getDireccion2(){
        return this.txtdireccion2.getText();
    }
    public String getTelefono1(){
        return this.txttelefono1.getText();
    }
    public String getTelefono2(){
        return this.txttelefono2.getText();
    }
    public String getEmail(){
        return this.txtemail.getText();
    }
    public String getFechaNacimiento(){
        return this.txtfechanacimiento.dateSelect("dd/MM/yyyy");
    }
    public boolean getTipoUsuario(){
        return this.chkusuario.isSelected();
    }
    public boolean getTipoCliente(){
        return this.chkcliente.isSelected();
    }
    public boolean getTipoProveedor(){
        return this.chkproveedor.isSelected();
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NuevoTercero().setVisible(true);
            }
        });
    }
    public javax.swing.JButton getBtnGuardar(){
        return this.btnguardar;
    }
    public void setBtnGuardar(javax.swing.JButton btnguardar){
        this.btnguardar=btnguardar;
    }
    public com.frame.Conf.TextFieldCustom getTxtDocumento(){
        return this.txtdocumento;
    }
    public void setTxtDocumento(com.frame.Conf.TextFieldCustom documento){
        this.txtdocumento=documento;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JCheckBox chkcliente;
    private javax.swing.JCheckBox chkproveedor;
    private javax.swing.JCheckBox chkusuario;
    private com.frame.Conf.ComboBoxCustom cmbtipodocumento;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.frame.Conf.TextFieldCustom txtdireccion;
    private com.frame.Conf.TextFieldCustom txtdireccion2;
    private com.frame.Conf.TextFieldCustom txtdocumento;
    private com.frame.Conf.TextFieldCustom txtemail;
    private com.frame.Conf.DatePickerCustom txtfechanacimiento;
    private com.frame.Conf.TextFieldCustom txtnombre;
    private com.frame.Conf.TextFieldCustom txttelefono1;
    private com.frame.Conf.TextFieldCustom txttelefono2;
    private org.jdatepicker.impl.UtilDateModel utilDateModel1;
    private org.jdatepicker.impl.UtilDateModel utilDateModel2;
    private org.jdatepicker.impl.UtilDateModel utilDateModel3;
    // End of variables declaration//GEN-END:variables
}
