/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.ControllerPermisos;
import Controller.ControllerTerceros;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class Terceros extends javax.swing.JFrame {
    private ControllerPermisos permisos;
    ControllerTerceros controller;
    /**
     * Creates new form Terceros
     */
    public Terceros() {
        this.controller=new ControllerTerceros();
        initComponents();
    }
    public Terceros(ControllerPermisos permisos) {
        this.permisos=permisos;
        initComponents();
        Object [][] rows = null;
        try{
            this.controller=new ControllerTerceros();
            ArrayList list=controller.loadDataGridAll();
            rows = new Object[list.size()][10];
            for(int i=0;i<list.size();i++){
                Model.Terceros ter=(Model.Terceros)list.get(i);
                rows[i]=new Object[]{ter.getTERID(),ter.getTERDOCUMENTO(),ter.getNOMBRECOMPLETO(),ter.getTERDIRECCION1(),ter.getTERDIRECCION2(),ter.getTERTELEFONO1(),ter.getTERTELEFONO2() };
            }
            this.controller.llenarComboTipoDocumento(this.cmbtipodocumento);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null, err.getMessage(), err.getCause().getMessage(),1);
        }
        javax.swing.table.DefaultTableModel model=new javax.swing.table.DefaultTableModel(rows,new String[]{"Id","Documento","Nombre Completo","Dir°1","Dir°2","Telefono°1","Telefono°2"}){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        model.isCellEditable(0,0);
        tterceros.setModel(model);
        tterceros.getColumnModel().getColumn(0).setMaxWidth(0);
        tterceros.getColumnModel().getColumn(0).setMinWidth(0);
        tterceros.getColumnModel().getColumn(0).setPreferredWidth(0);
        tterceros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tterceros.getColumnModel().getColumn(2).setPreferredWidth(300);
        tterceros.getColumnModel().getColumn(3).setPreferredWidth(180);
        tterceros.getColumnModel().getColumn(4).setPreferredWidth(180);
        tterceros.getColumnModel().getColumn(5).setPreferredWidth(120);
        tterceros.getColumnModel().getColumn(6).setPreferredWidth(120);
        for(int i=0;i<=6;i++){
            tterceros.getColumnModel().getColumn(i).setResizable(false);
        }
        tterceros.getTableHeader().setReorderingAllowed(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grptipobusqueda = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cmbtipodocumento = new com.frame.Conf.ComboBoxCustom();
        jLabel2 = new javax.swing.JLabel();
        txtdocumento = new com.frame.Conf.TextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        chkbuq1 = new javax.swing.JRadioButton();
        chkbuq2 = new javax.swing.JRadioButton();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tterceros = new javax.swing.JTable();
        txtnombre = new com.frame.Conf.TextFieldCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Terceros");

        jLabel1.setText("Tipo Documento");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Documento");

        txtdocumento.setFont(new java.awt.Font("Noto Sans", 0, 13)); // NOI18N
        txtdocumento.setPlaceholder("Documento");
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyPressed(evt);
            }
        });

        jLabel3.setText("Nombre Completo");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        grptipobusqueda.add(chkbuq1);
        chkbuq1.setSelected(true);
        chkbuq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkbuq1MouseClicked(evt);
            }
        });

        grptipobusqueda.add(chkbuq2);
        chkbuq2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkbuq2MouseClicked(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });

        tterceros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tterceros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tterceros.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tterceros);

        txtnombre.setEditable(false);
        txtnombre.setMargin(new java.awt.Insets(0, 5, 0, 0));
        txtnombre.setPlaceholder("Nombre Completo");
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkbuq1)
                            .addComponent(chkbuq2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbtipodocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkbuq1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkbuq2)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbuq2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbuq2MouseClicked
        if(this.chkbuq2.isSelected()){
            this.txtnombre.setEditable(true);
            this.txtdocumento.setEditable(false);
            this.cmbtipodocumento.setEnabled(false);
            try{
                this.cmbtipodocumento.setKey("1");
            }catch(Exception err){
                System.out.println(err.getMessage());
            }
            this.txtdocumento.setText("");
        }
    }//GEN-LAST:event_chkbuq2MouseClicked

    private void chkbuq1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbuq1MouseClicked
        if(this.chkbuq1.isSelected()){
            this.txtnombre.setEditable(false);
            this.txtdocumento.setEditable(true);
            this.cmbtipodocumento.setEnabled(true);
            this.txtnombre.setText("");
        }
    }//GEN-LAST:event_chkbuq1MouseClicked

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        this.eventBuscar();
    }//GEN-LAST:event_btnbuscarMouseClicked
    private void eventBuscar(){
        try{
            if(this.chkbuq1.isSelected()){
                DefaultTableModel dtm=(DefaultTableModel)this.tterceros.getModel();
                dtm.getDataVector().removeAllElements();
                dtm.fireTableDataChanged();
                if(!this.txtdocumento.getText().trim().equals("")){
                    Model.Terceros ter=this.controller.cargarTerceroId(this.cmbtipodocumento.getKey(),this.txtdocumento.getText());
                    if(ter!=null){
                        Object[] row={ter.getTERID(),ter.getTERDOCUMENTO(),ter.getNOMBRECOMPLETO(),ter.getTERDIRECCION1(),ter.getTERDIRECCION2(),ter.getTERTELEFONO1(),ter.getTERTELEFONO2()};
                        dtm.addRow(row);
                        this.tterceros.setModel(dtm);
                    }
                }else{
                    this.llenarGridCompleto();
                }
            }else{
                if(this.chkbuq2.isSelected()){
                    if(!this.txtnombre.getText().trim().equals("")){
                        this.llenarNombre(this.txtnombre.getText().trim().toUpperCase());
                    }else{
                        this.llenarGridCompleto();
                    }
                }
            }
        }catch(Exception err){
            JOptionPane.showMessageDialog(null, err.getMessage(),err.getCause().getMessage(),1);
        }
    }
    private void txtdocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyPressed
        if(evt.getKeyCode()==10){
            this.eventBuscar();
        }
    }//GEN-LAST:event_txtdocumentoKeyPressed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        if(evt.getKeyCode()==10){
            this.eventBuscar();
        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        this.txtnombre.setText(this.txtnombre.getText().toUpperCase());
    }//GEN-LAST:event_txtnombreKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.chkbuq2.setSelected(true);
        this.txtnombre.setEditable(true);
        this.txtdocumento.setEditable(false);
        this.cmbtipodocumento.setEnabled(false);
        try{
            this.cmbtipodocumento.setKey("1");
        }catch(Exception err){
            System.out.println(err.getMessage());
        }
        this.txtdocumento.setText("");
        this.eventBuscar();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.chkbuq1.setSelected(true);
        this.txtnombre.setEditable(false);
        this.txtdocumento.setEditable(true);
        this.cmbtipodocumento.setEnabled(true);
        this.txtnombre.setText("");
        this.eventBuscar();
    }//GEN-LAST:event_jLabel1MouseClicked
    private void llenarGridCompleto() throws Exception{
        try{
            ArrayList list=controller.loadDataGridAll();
            DefaultTableModel dtm=(DefaultTableModel)this.tterceros.getModel();
            dtm.getDataVector().removeAllElements();
            dtm.fireTableDataChanged();
            for(int i=0;i<list.size();i++){
                Model.Terceros ter=(Model.Terceros)list.get(i);
                Object[] row={ter.getTERID(),ter.getTERDOCUMENTO(),ter.getNOMBRECOMPLETO(),ter.getTERDIRECCION1(),ter.getTERDIRECCION2(),ter.getTERTELEFONO1(),ter.getTERTELEFONO2()};
                dtm.addRow(row);
                this.tterceros.setModel(dtm);
            }
        }catch(Exception err){
            throw new Exception(err.getMessage(),new Throwable("Error al cargar Grilla"));
        }
    }
    private void llenarNombre(String nombre) throws Exception{
        try{
            ArrayList list=controller.loadDataGridNombre(nombre);
            DefaultTableModel dtm=(DefaultTableModel)this.tterceros.getModel();
            dtm.getDataVector().removeAllElements();
            dtm.fireTableDataChanged();
            for(int i=0;i<list.size();i++){
                Model.Terceros ter=(Model.Terceros)list.get(i);
                Object[] row={ter.getTERID(),ter.getTERDOCUMENTO(),ter.getNOMBRECOMPLETO(),ter.getTERDIRECCION1(),ter.getTERDIRECCION2(),ter.getTERTELEFONO1(),ter.getTERTELEFONO2()};
                dtm.addRow(row);
                this.tterceros.setModel(dtm);
            }
        }catch(Exception err){
            throw new Exception(err.getMessage(),new Throwable("Error al cargar Grilla"));
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Terceros().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JRadioButton chkbuq1;
    private javax.swing.JRadioButton chkbuq2;
    private com.frame.Conf.ComboBoxCustom cmbtipodocumento;
    private javax.swing.ButtonGroup grptipobusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tterceros;
    private com.frame.Conf.TextFieldCustom txtdocumento;
    private com.frame.Conf.TextFieldCustom txtnombre;
    // End of variables declaration//GEN-END:variables
}
